name: weather_app
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.5
  geolocator: ^14.0.0
  http: ^1.4.0
  intl: ^0.20.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/app_logo.png'

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/house_01.png
    - assets/weather_01.png
    - assets/logo/app_logo_transparent.png
    - assets/logo/app_logo.png
